#!/bin/bash
#portappm
DATABASE_URL="https://raw.githubusercontent.com/PavelDobCZ23/Portable-Linux-App-Manager/main/database"
APPS_DIRECTORY=""
COMMAND=""
APP_NAME=""
FORCE_OPTION=false

# Get cli flags
while getopts "fc:a:d:" o; do
  case "${o}" in
    a)
      APP_NAME="${OPTARG}"
      ;;
    c)
      COMMAND="${OPTARG}"
      ;;
    d)
      APPS_DIRECTORY="${OPTARG}"
      ;;
    f)
      FORCE_OPTION=true
      ;;
    *)
      echo "Fatal Error! Invalid flag '${o}' found!"
      exit 1
  esac
done

# ## Parse main directory with applications
if [[ -z $APPS_DIRECTORY ]]; then APPS_DIRECTORY="$HOME/Apps"; fi
if [[ ${APPS_DIRECTORY:0-1} == "/" ]]; then APPS_DIRECTORY="${APPS_DIRECTORY%?}"; fi
if [[ ! -d $APPS_DIRECTORY ]]; then
  echo "'$APPS_DIRECTORY' doesn't exist!"
  exit 1
fi

# # Basic functions 
# Gets the depth of a given path
path_depth() {
    local CHECK_PATH="$1"
    local DEPTH_COUNT=0
    CHECK_PATH=$(echo "$CHECK_PATH" | sed 's:/*$::')
    DEPTH_COUNT=$(echo "$CHECK_PATH" | awk -F'[^/]*/+' '{print NF-1}')
    if [[ DEPTH_COUNT -lt 0 ]]; then DEPTH_COUNT=0; fi
    echo "$DEPTH_COUNT"
}

# Removes given folder, but prevents dangerous rm -rf!
remove_folder () {
  local REMOVE_PATH="$1"
  if [[ $(path_depth "$REMOVE_PATH") -lt 4 ]];
  then
    echo "Can't remove '$REMOVE_PATH', dangerous 'rm -rf' detected!"
  else
    echo "Removing '$REMOVE_PATH'."
    rm -rf "$REMOVE_PATH"
  fi
}

# Returns with fail(1) if any of the required files are missing, otherwise returns with success(0)
check_valid_app () {
  local CHECK_APP_NAME="$1"
  local CHECK_APP_DIR="$APPS_DIRECTORY/$APP_NAME"
  if [[ ! -f "$CHECK_APP_DIR/app.conf" ]]; then
    echo "$CHECK_APP_NAME | app.conf not found!"
    return 1
  fi;
  if [[ ! -x "$CHECK_APP_DIR/app-update.sh" ]]; then
    echo "$CHECK_APP_NAME | app-update.sh not found or not executable!"
    return 1
  fi;
  return 0
}

# Reads the config file of the app and saves the configuration into variables accessible by the caller
read_app_config () {
  local CONFIG_APP_NAME="$1"
  local CONFIG_FILE="$APPS_DIRECTORY/$CONFIG_APP_NAME/app.conf"
  local SECTION="None"
  while IFS= read -r LINE
  do
    # Check current config section
    if [[ $LINE =~ ^\ *\[.*\]\ *$ ]]; then #Regex that checks for characters between [] and allows spaces around
        SECTION=$(echo "$LINE" | awk -F'[][]+' '{print $2}') #if [[ "$SUBSECTION" =~ ^\ *$ ]]; then echo "Empty"; fi
        continue
    fi
    # Read Key-Value pairs
    if [[ $LINE =~ ^\ *\#.*$ ]]; then continue; fi
    KEY=$(echo "$LINE" | awk -F' *=' '{print $1}' | sed 's/^[[:space:]]*//')
    VALUE=$(
      echo "$LINE" | awk -F: '{ n=index($0,"=");print substr($0,n+1)}' | # Splits by the 1st "=" and returns the 2nd half
      sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//' # Removes trailing spaces
    )
    
    # Save values in config into variables
    if [[ $SECTION == "General" ]]; then
      if [[ $KEY == "Exec" ]];then EXECUTABLE_PATH=$VALUE;fi
      if [[ $KEY == "Type" ]];then EXECUTABLE_TYPE=$VALUE;fi
      if [[ $KEY == "ExtractFolder" ]];then EXTRACT_FOLDER=$VALUE;fi
      if [[ $KEY == "ArchiveStrip" ]];then ARCHIVE_STRIP=$VALUE;fi
      if [[ $KEY == "RemoveBeforeUpdate" ]];then RM_BEFORE_UPDATE=$VALUE;fi
      if [[ $KEY == "DisableUpdates" ]];then DISABLE_UPDATES=$VALUE;fi
    elif [[ $SECTION == "Desktop" ]]; then
      if [[ $KEY == "Name" ]];then DESKTOP_NAME=$VALUE;fi
      if [[ $KEY == "Icon" ]];then DESKTOP_ICON=$VALUE;fi
      if [[ $KEY == "GenericName" ]];then DESKTOP_GENERIC_NAME=$VALUE;fi
      if [[ $KEY == "Terminal" ]];then DESKTOP_TERMINAL=$VALUE;fi
      if [[ $KEY == "NoDisplay" ]];then DESKTOP_NO_DISPLAY=$VALUE;fi
      if [[ $KEY == "Arguments" ]];then EXECUTABLE_ARGS=$VALUE;fi
      if [[ $KEY == "EnvVariables" ]];then EXECUTABLE_ENV=$VALUE;fi
      if [[ $KEY == "PreLaunch" ]];then EXECUTABLE_PRE_LAUNCH=$VALUE;fi
    fi
  done < "$CONFIG_FILE"
}

get_app_executable () {
  local ENV_STRING=""
  read_app_config "$APP_NAME" 1>&2> /dev/null
  if [[ -n $EXECUTABLE_ENV ]]; then
    ENV_STRING="env $EXECUTABLE_ENV"
  fi
  local EXEC_PATH="$APPS_DIRECTORY/$APP_NAME/$EXECUTABLE_PATH"
  echo "$ENV_STRING $EXECUTABLE_PRE_LAUNCH '$EXEC_PATH' $EXECUTABLE_ARGS"
}

# # Command functions
# ## Checks for available updates and updates the app if possible
update_app () {
  APP_NAME="$1"
  if ! check_valid_app "$APP_NAME"; then 
    echo "$APP_NAME | Not a valid app, can't update!"
    exit 1
  fi
  APP_DIR="$APPS_DIRECTORY/$APP_NAME"
  VERSION_FILE="$APP_DIR/.version"
  INSTALLED_VERSION=$(awk 'NR==1{ print; exit }' "$VERSION_FILE") # Gets the 1st line of .version file
  RM_BEFORE_UPDATE=false
  ARCHIVE_STRIP=0
  UPDATE_SCRIPT="$APP_DIR/app-update.sh"
  # Get variables from a config file
  read_app_config "$APP_NAME"
  if [[ "$DISABLE_UPDATES" = true ]]; then
    echo "$APP_NAME | Updates are disabled in 'app.conf' for this app."
    return 0
  fi
  if [[ -z $EXECUTABLE_PATH ]]; then
    echo "$APP_NAME | Configuration failure! 'General.Exec' is not set! Make sure to set it to a valid file name!"
    return 1
  fi
  # Check if newer version is available
  LATEST_VERSION="$("$UPDATE_SCRIPT" -v)"
  if [[ -z $LATEST_VERSION ]]; then # Handle empty error
    echo "$APP_NAME | Failed to get the latest version of the app!"
    return 1
  fi
  if [[ $LATEST_VERSION =~ ^Fatal\ Error\!.*$ ]]; then # Handle errors
    echo "$APP_NAME | $LATEST_VERSION"
    return 1
  fi
  if [[ "$INSTALLED_VERSION" == "$LATEST_VERSION" ]]; then
    echo "$APP_NAME | Up To Date! Version: $LATEST_VERSION"
    return 0
  fi
  # Continue if an update is available
  echo "$APP_NAME | New version found! $LATEST_VERSION (Installed version: $INSTALLED_VERSION)"
  DOWNLOAD_URL="$("$UPDATE_SCRIPT" -u)"
  if [[ -z $DOWNLOAD_URL ]]; then # Handle empty error
    echo "$APP_NAME | Failed to get the download URL for the app!"
    return 1
  fi
  if [[ $DOWNLOAD_URL =~ ^Fatal\ Error\!.*$ ]]; then # Handle errors
    echo "$APP_NAME | $DOWNLOAD_URL"
    return 1
  fi

  # Download the update and return if it fails
  echo "$APP_NAME | Downloading new version from '$DOWNLOAD_URL'."
  TEMP_FILE="$APP_DIR/temp-download-file"
  BIN_PATH="$APP_DIR/$EXECUTABLE_PATH"
  if ! wget --content-disposition -q --show-progress "$DOWNLOAD_URL" -O "$TEMP_FILE"; then
    echo "$APP_NAME | Failed to download."
    return 1
  fi

  # Remove Before Update
  if [[ "$RM_BEFORE_UPDATE" = true ]]; then
    echo "$APP_NAME | Removing binary file(s) before updating."
    rm -f "$APPS_DIRECTORY/$APP_NAME/$EXECUTABLE_PATH"
    if [[ -n $EXTRACT_FOLDER ]]; then
      REMOVE_PATH="$APPS_DIRECTORY/$APP_NAME/$EXTRACT_FOLDER"
      remove_folder "$REMOVE_PATH"
    fi
  fi

  # Extract the downloaded file
  if [[ "$EXECUTABLE_TYPE" == "SingleBin" ]]; then
    echo "$APP_NAME | Saving the updated binary to '$BIN_PATH'."
    mv -f "$TEMP_FILE" "$BIN_PATH"
  elif [[ "$EXECUTABLE_TYPE" == "BinArchive" ]]; then
    EXTRACT_PATH="$APP_DIR"
    if [[ -n $EXTRACT_FOLDER ]]; then EXTRACT_PATH="$APP_DIR/$EXTRACT_FOLDER"; fi
    if [[ ! -d $EXTRACT_PATH ]]; then mkdir -p "$EXTRACT_PATH"; fi
    echo "$APP_NAME | Extracting the updated archive to '$EXTRACT_PATH'."
    tar -xf "$TEMP_FILE" -C "$EXTRACT_PATH" --strip "$ARCHIVE_STRIP" --overwrite
    rm -f "$TEMP_FILE"
  else
    echo "$APP_NAME | Configuration failure! 'General.Type' is set to an unrecognised value - '$EXECUTABLE_TYPE' Allowed values: 'SingleBin','BinArchive'"
    rm -f "$TEMP_FILE"
    return 1
  fi

  # Finishing up
  echo "$APP_NAME | Setting executable permissions for the binary and saving the installed version."
  chmod +x "$BIN_PATH"
  echo "$LATEST_VERSION" > "$VERSION_FILE"
  echo "$APP_NAME | Done updating!"
}

create_app_shortcut() {
  APP_NAME="$1"
  if ! check_valid_app "$APP_NAME"; then 
    echo "$APP_NAME | Not a valid app, can't create shortcut!"
    exit 1
  fi
  DESKTOP_FILE_DIR="$HOME/.local/share/applications/Portable"
  APP_DESKTOP_FILE="$DESKTOP_FILE_DIR/$APP_NAME.desktop"
  if [[ -f "$APP_DESKTOP_FILE" ]]; then
    echo "Desktop file '$APP_DESKTOP_FILE' already exists."
    return 0
  fi
  # Get desktop entries
  DESKTOP_EXEC=$(get_app_executable "$APP_NAME")
  read_app_config "$APP_NAME"
  if [[ $DESKTOP_ICON =~ ^\.\/ ]]; then
    DESKTOP_ICON="$APPS_DIRECTORY/$APP_NAME/${DESKTOP_ICON:2}"
  fi

  echo "Creating desktop file '$APP_DESKTOP_FILE'."
  echo "[Desktop Entry]" > "$APP_DESKTOP_FILE"
  {
    echo "Exec=$DESKTOP_EXEC";
    echo "Path=$APPS_DIRECTORY/$APP_NAME/";
    echo "Type=Application";
    echo "Name=$DESKTOP_NAME";
    echo "Icon=$DESKTOP_ICON";
    echo "GenericName=$DESKTOP_GENERIC_NAME";
    echo "Comment=$DESKTOP_COMMENT";
    echo "MimeType=$DESKTOP_MIME_TYPE";
    echo "Categories=$DESKTOP_CATEGORIES";
    echo "Keywords=$DESKTOP_KEYWORDS";
    echo "Terminal=$DESKTOP_TERMINAL";
    echo "NoDisplay=$DESKTOP_NO_DISPLAY";
  } >> "$APP_DESKTOP_FILE"
}

update_all_apps () {
  for APP_PATH in "$APPS_DIRECTORY"/*/; do
    if [ ! -d "$APP_PATH" ]; then continue; fi # Skip files
    APP_NAME="$(basename "$APP_PATH")"
    if check_valid_app "$APP_NAME"; then
        update_app "$APP_NAME"
    else
      for SUB_APP_PATH in "$APP_PATH"/*/; do
        if [ ! -d "$SUB_APP_PATH" ]; then continue; fi # Skip files
        SUB_APP_NAME="$APP_NAME/$(basename "$SUB_APP_PATH")"
        if check_valid_app "$SUB_APP_NAME"; then
          update_app "$SUB_APP_NAME"
        fi
      done
      continue
    fi
  done
}

create_all_app_shortcuts () {
    for APP_PATH in "$APPS_DIRECTORY"/*/; do
    if [ ! -d "$APP_PATH" ]; then continue; fi # Skip files
    APP_NAME="$(basename "$APP_PATH")"
    if check_valid_app "$APP_NAME"; then
        create_app_shortcut "$APP_NAME"
    else
      for SUB_APP_PATH in "$APP_PATH"/*/; do
        if [ ! -d "$SUB_APP_PATH" ]; then continue; fi # Skip files
        SUB_APP_NAME="$APP_NAME/$(basename "$SUB_APP_PATH")"
        if check_valid_app "$SUB_APP_NAME"; then
          create_app_shortcut "$SUB_APP_NAME"
        fi
      done
      continue
    fi
  done
}

add_app () {
  local NEW_APP_NAME="$1"
  if check_valid_app "$NEW_APP_NAME"; then
    echo "App '$NEW_APP_NAME' can't be added, because it already exists!"
    exit 1
  fi

  local NEW_APP_DIR="$APPS_DIRECTORY/$NEW_APP_NAME"
  DEFAULT_FILES_DIR="$(dirname "$(realpath "$0")")/default"
  NEW_APP_BASENAME="$(basename "$NEW_APP_DIR")" # | tr '[:upper:]' '[:lower:]' | tr ' _' '-'
  APP_DB_URL="$DATABASE_URL/$NEW_APP_BASENAME"
  
  echo "Creating new app in '$NEW_APP_DIR'."
  mkdir -p "$NEW_APP_DIR"
  if wget --spider -q "$APP_DB_URL/app.conf"; then # Files for apps in the database
    echo "Name '$NEW_APP_BASENAME' found in the database. Using pre-filled files."
    wget --content-disposition -q --show-progress "$APP_DB_URL/app.conf" -O "$NEW_APP_DIR/app.conf"
    wget --content-disposition -q --show-progress "$APP_DB_URL/app-update.sh" -O "$NEW_APP_DIR/app-update.sh"
    # Try to download any possible icons
    if wget --spider -q "$APP_DB_URL/icon.svg"; then
      wget --content-disposition -q --show-progress "$APP_DB_URL/icon.svg" -O "$NEW_APP_DIR/icon.svg"
    elif wget --spider -q "$APP_DB_URL/icon.png"; then
      wget --content-disposition -q --show-progress "$APP_DB_URL/icon.png" -O "$NEW_APP_DIR/icon.png"
    elif wget --spider -q "$APP_DB_URL/icon.ico"; then
      wget --content-disposition -q --show-progress "$APP_DB_URL/icon.ico" -O "$NEW_APP_DIR/icon.ico"
    fi
  else # Default empty files
    echo "Creating default template app."
    cp "$DEFAULT_FILES_DIR/app.conf" "$NEW_APP_DIR/app.conf"
    cp "$DEFAULT_FILES_DIR/app-update.sh" "$NEW_APP_DIR/app-update.sh"
  fi
  chmod +x "$NEW_APP_DIR/app-update.sh"
  return
}

# Verifies basic properties of the required files to check if they are valid and corrects them if they aren't
verify_app () {
  return
}

# Forces reinstallation of the app
reinstall_app () {
  APP_NAME=$1
  if ! check_valid_app "$APP_NAME"; then 
    echo "$APP_NAME | Not a valid app, can't reinstall!"
    exit 1
  fi
  read_app_config "$APP_NAME"
  echo "$APP_NAME | This process will remove the '.version' file and the app's binary file(s) and trigger update for the app to force its installation."
  rm -f "$APPS_DIRECTORY/$APP_NAME/.version"
  rm -f "$APPS_DIRECTORY/$APP_NAME/$EXECUTABLE_PATH"
  if [[ -n $EXTRACT_FOLDER ]]; then
    REMOVE_PATH="$APPS_DIRECTORY/$APP_NAME/$EXTRACT_FOLDER"
    remove_folder "$REMOVE_PATH"
  fi
  update_app "$APP_NAME"
}

run_app () {
  APP_NAME=$1
  APP_EXEC=$(get_app_executable "$APP_NAME")
  echo "Running:"
  echo "$APP_EXEC"
  eval "$APP_EXEC"
}

# # Selecting the command
if [[ $COMMAND = "run" ]]; then
  run_app "$APP_NAME"
elif [[ "$COMMAND" = "update" ]]; then
  if [[ -z $APP_NAME ]]; then
    update_all_apps
  else
    update_app "$APP_NAME"
  fi
elif [[ "$COMMAND" = "add" ]]; then
  add_app "$APP_NAME"
elif [[ "$COMMAND" = "reinstall" ]]; then
  reinstall_app "$APP_NAME"
elif [[ "$COMMAND" = "shortcut" ]]; then
  if [[ -z $APP_NAME ]]; then
    create_all_app_shortcuts
  else
    create_app_shortcut "$APP_NAME"
  fi
fi